/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Body.Forms.Add;

import GUI.Body.BodyGUI;
import static GUI.Main.connection;
import Logic.SpeStudy;
import Logic.Study;
import Logic.Subject;
import Utils.Calendar.Day;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author dobleme
 */
public class FormAddSpecialStudyGUI extends javax.swing.JPanel {

  /**
   * Creates new form FormAltaEstudi
   *
   * @param body
   * @param speStudy
   */
  public FormAddSpecialStudyGUI(BodyGUI body, SpeStudy speStudy) {
    this.body = body;
    this.speStudy = speStudy;
    this.subject = speStudy.getSpeAttr();
    initComponents();
    enableSpinners();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelCalendar = new javax.swing.JLabel();
        jLabelThursday = new javax.swing.JLabel();
        jLabelFriday = new javax.swing.JLabel();
        jRadioButtonMorning = new javax.swing.JRadioButton();
        jRadioButtonEvening = new javax.swing.JRadioButton();
        jRadioButtonEveningMorning = new javax.swing.JRadioButton();
        jSpinnerMonday = new javax.swing.JSpinner();
        jSpinnerTuesday = new javax.swing.JSpinner();
        jSpinnerWednesday = new javax.swing.JSpinner();
        jSpinnerThursday = new javax.swing.JSpinner();
        jSpinnerFriday = new javax.swing.JSpinner();
        jLabelMonday = new javax.swing.JLabel();
        jLabelTuesday = new javax.swing.JLabel();
        jLabelWednseday = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jButtonAssignations = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1150, 670));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Alta Estudi Especial");

        jSeparator1.setForeground(new java.awt.Color(241, 241, 241));

        jLabelCalendar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelCalendar.setText("Horari:");

        jLabelThursday.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelThursday.setText("Dj");

        jLabelFriday.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelFriday.setText("Dv");

        jRadioButtonMorning.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonMorning);
        jRadioButtonMorning.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonMorning.setSelected(true);
        jRadioButtonMorning.setText("Torn Matí");

        jRadioButtonEvening.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonEvening);
        jRadioButtonEvening.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonEvening.setText("Torn Horabaixa");

        jRadioButtonEveningMorning.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonEveningMorning);
        jRadioButtonEveningMorning.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonEveningMorning.setText("Torn Horabaixa/Matí");

        jSpinnerMonday.setModel(new javax.swing.SpinnerNumberModel(0, 0, 7, 1));
        jSpinnerMonday.setEnabled(false);

        jSpinnerTuesday.setModel(new javax.swing.SpinnerNumberModel(0, 0, 7, 1));
        jSpinnerTuesday.setEnabled(false);

        jSpinnerWednesday.setModel(new javax.swing.SpinnerNumberModel(0, 0, 7, 1));
        jSpinnerWednesday.setEnabled(false);

        jSpinnerThursday.setModel(new javax.swing.SpinnerNumberModel(0, 0, 7, 1));
        jSpinnerThursday.setEnabled(false);

        jSpinnerFriday.setModel(new javax.swing.SpinnerNumberModel(0, 0, 7, 1));
        jSpinnerFriday.setEnabled(false);

        jLabelMonday.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelMonday.setText("Dll");

        jLabelTuesday.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelTuesday.setText("Dm");

        jLabelWednseday.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelWednseday.setText("Dx");

        jButtonCancel.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonAssignations.setBackground(new java.awt.Color(241, 241, 241));
        jButtonAssignations.setText("Assignació Aula/Professor");
        jButtonAssignations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssignationsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCalendar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMonday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerMonday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabelTuesday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabelWednseday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabelThursday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerThursday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabelFriday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerFriday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonCancel)
                            .addGap(223, 223, 223)
                            .addComponent(jButtonAssignations))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButtonMorning)
                            .addGap(80, 80, 80)
                            .addComponent(jRadioButtonEvening)
                            .addGap(104, 104, 104)
                            .addComponent(jRadioButtonEveningMorning))))
                .addGap(279, 279, 279))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCalendar)
                    .addComponent(jSpinnerMonday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerThursday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerFriday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMonday)
                    .addComponent(jLabelTuesday)
                    .addComponent(jLabelWednseday)
                    .addComponent(jLabelThursday)
                    .addComponent(jLabelFriday))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonEveningMorning)
                    .addComponent(jRadioButtonEvening)
                    .addComponent(jRadioButtonMorning))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAssignations)
                    .addComponent(jButtonCancel))
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
      body.showFormAddStudy();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonAssignationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAssignationsActionPerformed
      int total = (Integer) jSpinnerMonday.getValue() + (Integer) jSpinnerTuesday.getValue() + (Integer) jSpinnerWednesday.getValue() + (Integer) jSpinnerThursday.getValue() + (Integer) jSpinnerFriday.getValue();

      if (total == 0) {
        String msg = "<html>"
                + "<h4>No es pot assignar per que no heu introduit cap hora.</h4>"
                + "<p>"
                + "</p></html>";
        javax.swing.JLabel label = new javax.swing.JLabel(msg);
        label.setFont(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12));
        JOptionPane.showMessageDialog(this, label, "Error Alta", JOptionPane.ERROR_MESSAGE);
      } else {
        Study.Turn turn = Study.Turn.morning;
        if (jRadioButtonEvening.isSelected()) {
          turn = Study.Turn.evening;
        } else if (jRadioButtonEveningMorning.isSelected()) {
          turn = Study.Turn.morningAndEvening;
        }

        ArrayList<Day> auxDays = new ArrayList<>();
        if ((Integer) jSpinnerMonday.getValue() > 0) {
          auxDays.add(new Day(Day.DayOfWeek.Monday, 0, (Integer) jSpinnerMonday.getValue()));
        }
        if ((Integer) jSpinnerTuesday.getValue() > 0) {
          auxDays.add(new Day(Day.DayOfWeek.Tuesday, 0, (Integer) jSpinnerTuesday.getValue()));
        }
        if ((Integer) jSpinnerWednesday.getValue() > 0) {
          auxDays.add(new Day(Day.DayOfWeek.Wednesday, 0, (Integer) jSpinnerWednesday.getValue()));
        }
        if ((Integer) jSpinnerThursday.getValue() > 0) {
          auxDays.add(new Day(Day.DayOfWeek.Thursday, 0, (Integer) jSpinnerThursday.getValue()));
        }
        if ((Integer) jSpinnerFriday.getValue() > 0) {
          auxDays.add(new Day(Day.DayOfWeek.Friday, 0, (Integer) jSpinnerFriday.getValue()));
        }

        Day days[] = new Day[auxDays.size()];
        days = auxDays.toArray(days);

        Utils.Calendar.Calendar cal = new Utils.Calendar.Calendar(connection, total / days.length, days.length, turn, days);

        subject.setCalendar(cal);

        body.showFormAssignationsSubject(subject, speStudy, false);
        
      }
    }//GEN-LAST:event_jButtonAssignationsActionPerformed

  private void enableSpinners() {
    boolean activeSpinner[] = {false, false, false, false, false};
    Calendar start = Calendar.getInstance();
    start.setTime(subject.getStartDate());

    Calendar finish = Calendar.getInstance();
    finish.setTime(subject.getFinishDate());

    // Activa spinners
    int day = 0;
    while (start.getTime().compareTo(finish.getTime()) < 1 && day < 5) {
      switch (start.get(Calendar.DAY_OF_WEEK)) {
        case 2:
          jSpinnerMonday.setEnabled(true);
          activeSpinner[0] = true;
          day++;
          break;
        case 3:
          jSpinnerTuesday.setEnabled(true);
          activeSpinner[1] = true;
          day++;
          break;
        case 4:
          jSpinnerWednesday.setEnabled(true);
          activeSpinner[2] = true;
          day++;
          break;
        case 5:
          jSpinnerThursday.setEnabled(true);
          activeSpinner[3] = true;
          day++;
          break;
        case 6:
          jSpinnerFriday.setEnabled(true);
          activeSpinner[4] = true;
          day++;
          break;
      }
      start.add(Calendar.DATE, 1);
    }

    //Deactivate spinners
    for (int i = 0; i < 5; i++) {
      switch (i) {
        case 0:
          if (!activeSpinner[0]) {
            jSpinnerMonday.setEnabled(false);
          }
          break;
        case 1:
          if (!activeSpinner[1]) {
            jSpinnerTuesday.setEnabled(false);
          }
          break;
        case 2:
          if (!activeSpinner[2]) {
            jSpinnerWednesday.setEnabled(false);
          }
          break;
        case 3:
          if (!activeSpinner[3]) {
            jSpinnerThursday.setEnabled(false);
          }
          break;
        case 4:
          if (!activeSpinner[4]) {
            jSpinnerFriday.setEnabled(false);
          }
          break;
      }
    }
    repaint();
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAssignations;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCalendar;
    private javax.swing.JLabel jLabelFriday;
    private javax.swing.JLabel jLabelMonday;
    private javax.swing.JLabel jLabelThursday;
    private javax.swing.JLabel jLabelTuesday;
    private javax.swing.JLabel jLabelWednseday;
    private javax.swing.JRadioButton jRadioButtonEvening;
    private javax.swing.JRadioButton jRadioButtonEveningMorning;
    private javax.swing.JRadioButton jRadioButtonMorning;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerFriday;
    private javax.swing.JSpinner jSpinnerMonday;
    private javax.swing.JSpinner jSpinnerThursday;
    private javax.swing.JSpinner jSpinnerTuesday;
    private javax.swing.JSpinner jSpinnerWednesday;
    // End of variables declaration//GEN-END:variables
    private final BodyGUI body;
  private final SpeStudy speStudy;
  private final Subject subject;
}
