package GUI.Body.Forms.Add;

import GUI.Body.BodyGUI;
import static GUI.Main.connection;
import GUI.Utils.Dialogs;
import Logic.Classroom;
import Logic.Classroom.ClassroomType;
import javax.swing.JOptionPane;

/**
 *
 * @author Pere Balaguer Gimeno
 * @author Lluc Martorell Medina
 */
public class FormAddClassroomGUI extends javax.swing.JPanel {

    /**
     * Creates new form FormAltaAula
     *
     * @param body Punter al cos que gestiona el CardLayout
     */
    public FormAddClassroomGUI(BodyGUI body) {
        this.body = body;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitleForm = new javax.swing.JLabel();
        jLabelClassroomType = new javax.swing.JLabel();
        jLabelCapacity = new javax.swing.JLabel();
        jComboBoxClassroomType = new javax.swing.JComboBox();
        jButtonAddClassroom = new javax.swing.JButton();
        jSeparatorTitleForm = new javax.swing.JSeparator();
        jSpinnerCapacity = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1150, 670));

        jLabelTitleForm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelTitleForm.setForeground(new java.awt.Color(255, 51, 51));
        jLabelTitleForm.setText("Alta Aula");

        jLabelClassroomType.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelClassroomType.setText("Tipus d'aula:");

        jLabelCapacity.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelCapacity.setText("Capacitat:");

        jComboBoxClassroomType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E" }));
        jComboBoxClassroomType.setMaximumSize(new java.awt.Dimension(550, 24));
        jComboBoxClassroomType.setMinimumSize(new java.awt.Dimension(550, 24));
        jComboBoxClassroomType.setPreferredSize(new java.awt.Dimension(550, 24));

        jButtonAddClassroom.setBackground(new java.awt.Color(0, 214, 121));
        jButtonAddClassroom.setText("Tramitar Alta");
        jButtonAddClassroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddClassroomActionPerformed(evt);
            }
        });

        jSeparatorTitleForm.setForeground(new java.awt.Color(241, 241, 241));
        jSeparatorTitleForm.setMinimumSize(new java.awt.Dimension(1000, 10));
        jSeparatorTitleForm.setPreferredSize(new java.awt.Dimension(1000, 10));

        jSpinnerCapacity.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinnerCapacity.setMinimumSize(new java.awt.Dimension(28, 28));
        jSpinnerCapacity.setPreferredSize(new java.awt.Dimension(28, 28));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelTitleForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparatorTitleForm, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAddClassroom)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClassroomType)
                            .addComponent(jLabelCapacity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerCapacity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxClassroomType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitleForm, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparatorTitleForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClassroomType)
                    .addComponent(jComboBoxClassroomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCapacity))
                .addGap(150, 150, 150)
                .addComponent(jButtonAddClassroom)
                .addGap(78, 78, 78))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddClassroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddClassroomActionPerformed
        int capacity = (Integer) jSpinnerCapacity.getValue();

        Classroom c = new Classroom(connection, capacity, Classroom.stringToEnum((String) jComboBoxClassroomType.getSelectedItem()));
        c = connection.storeClassroom(c);

        if (c != null) {
            Dialogs.successfulAdd(this, "L'aula", String.valueOf(c.getId()));
        } else {
            Dialogs.notSuccessfulAdd(this, "L'aula");
        }

        body.showFormAddClassroom();
    }//GEN-LAST:event_jButtonAddClassroomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddClassroom;
    private javax.swing.JComboBox jComboBoxClassroomType;
    private javax.swing.JLabel jLabelCapacity;
    private javax.swing.JLabel jLabelClassroomType;
    private javax.swing.JLabel jLabelTitleForm;
    private javax.swing.JSeparator jSeparatorTitleForm;
    private javax.swing.JSpinner jSpinnerCapacity;
    // End of variables declaration//GEN-END:variables
    private final BodyGUI body;
}
