package GUI.Body.Forms.Add;

import Definitions.Defs;
import GUI.Body.BodyGUI;
import static GUI.Main.connection;
import GUI.Utils.Dialogs;
import Logic.Teacher;
import Utils.Exceptions.DBException;
import java.awt.Color;

/**
 *
 * @author Pere Balaguer Gimeno
 * @author Lluc Martorell Medina
 */
public class FormAddTeacherGUI extends javax.swing.JPanel {

  /**
   * Creates new form Form
   *
   * @param body Punter al cos que gestiona el CardLayout
   */
  public FormAddTeacherGUI(BodyGUI body) {
    this.body = body;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitleForm = new javax.swing.JLabel();
        jSeparatorTitleForm = new javax.swing.JSeparator();
        jLabelName = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelSecondName = new javax.swing.JLabel();
        jLabelNif = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jButtonAddTeacher = new javax.swing.JButton();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldSecondName = new javax.swing.JTextField();
        jLabelWarningName = new javax.swing.JLabel();
        jLabelWarningFirstName = new javax.swing.JLabel();
        jLabelWarningSecondName = new javax.swing.JLabel();
        jFormattedTextFieldPhone = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNif = new javax.swing.JFormattedTextField();
        jLabelWarningNif = new javax.swing.JLabel();
        jLabelWarningPhone = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1150, 670));

        jLabelTitleForm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelTitleForm.setForeground(new java.awt.Color(255, 51, 51));
        jLabelTitleForm.setText("Alta Professor");

        jSeparatorTitleForm.setForeground(new java.awt.Color(241, 241, 241));

        jLabelName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelName.setText("Nom:");

        jLabelFirstName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelFirstName.setText("Primer Cognom:");

        jLabelSecondName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelSecondName.setText("Segon Cognom:");

        jLabelNif.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelNif.setText("NIF:");

        jLabelPhone.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelPhone.setText("Telèfon:");

        jButtonAddTeacher.setBackground(new java.awt.Color(0, 214, 121));
        jButtonAddTeacher.setText("Tramitar Alta");
        jButtonAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTeacherActionPerformed(evt);
            }
        });

        jTextFieldName.setMaximumSize(new java.awt.Dimension(550, 28));
        jTextFieldName.setMinimumSize(new java.awt.Dimension(550, 28));
        jTextFieldName.setPreferredSize(new java.awt.Dimension(550, 28));
        jTextFieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNameFocusLost(evt);
            }
        });

        jTextFieldFirstName.setMaximumSize(new java.awt.Dimension(550, 28));
        jTextFieldFirstName.setMinimumSize(new java.awt.Dimension(550, 28));
        jTextFieldFirstName.setPreferredSize(new java.awt.Dimension(550, 28));
        jTextFieldFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFirstNameFocusLost(evt);
            }
        });

        jTextFieldSecondName.setMaximumSize(new java.awt.Dimension(550, 28));
        jTextFieldSecondName.setMinimumSize(new java.awt.Dimension(550, 28));
        jTextFieldSecondName.setPreferredSize(new java.awt.Dimension(550, 28));
        jTextFieldSecondName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldSecondNameFocusLost(evt);
            }
        });

        jLabelWarningName.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        jLabelWarningName.setText("(Màxim 30 caràcters)");
        jLabelWarningName.setToolTipText("");

        jLabelWarningFirstName.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        jLabelWarningFirstName.setText("(Màxim 60 caràcters)");

        jLabelWarningSecondName.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        jLabelWarningSecondName.setText("(Màxim 60 caràcters)");

        try {
            jFormattedTextFieldPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### ### ###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPhone.setMaximumSize(new java.awt.Dimension(200, 28));
        jFormattedTextFieldPhone.setMinimumSize(new java.awt.Dimension(200, 28));
        jFormattedTextFieldPhone.setPreferredSize(new java.awt.Dimension(200, 28));
        jFormattedTextFieldPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldPhoneFocusLost(evt);
            }
        });

        try {
            jFormattedTextFieldNif.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########L")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNif.setText("");
        jFormattedTextFieldNif.setToolTipText("");
        jFormattedTextFieldNif.setMaximumSize(new java.awt.Dimension(200, 28));
        jFormattedTextFieldNif.setMinimumSize(new java.awt.Dimension(200, 28));
        jFormattedTextFieldNif.setPreferredSize(new java.awt.Dimension(200, 28));
        jFormattedTextFieldNif.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldNifFocusLost(evt);
            }
        });

        jLabelWarningNif.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        jLabelWarningNif.setText("(12345678A)");

        jLabelWarningPhone.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        jLabelWarningPhone.setText("(971 111 222)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelTitleForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparatorTitleForm)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAddTeacher)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelName)
                            .addComponent(jLabelFirstName)
                            .addComponent(jLabelSecondName)
                            .addComponent(jLabelNif))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSecondName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelWarningName)
                            .addComponent(jLabelWarningFirstName)
                            .addComponent(jLabelWarningSecondName)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldNif, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)
                                        .addComponent(jLabelPhone))
                                    .addComponent(jLabelWarningNif))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelWarningPhone)
                                    .addComponent(jFormattedTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparatorTitleForm, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitleForm))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWarningName)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWarningFirstName)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSecondName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWarningSecondName)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhone)
                    .addComponent(jLabelNif)
                    .addComponent(jFormattedTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWarningNif)
                    .addComponent(jLabelWarningPhone))
                .addGap(60, 60, 60)
                .addComponent(jButtonAddTeacher)
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTeacherActionPerformed
      wrongFormat &= 27;
      if (wrongFormat > 0) {
        Dialogs.wrongFormat(this);
      } else {
        Teacher t = new Teacher(connection, Defs.formatName(jTextFieldName.getText()), Defs.formatString(jTextFieldFirstName.getText()),
                Defs.formatString(jTextFieldSecondName.getText()), Defs.formatNif(jFormattedTextFieldNif.getText()), Defs.formatPhone(jFormattedTextFieldPhone.getText()));
        try {
          t = connection.storeTeacher(t);
        } catch (DBException ex) {
        } finally {
          if (t != null) {
            Dialogs.successfulAdd(this, "El professor", t.getName());
            body.showFormAddTeacher();
          } else {
            Dialogs.notSuccessfulAdd(this, "El professor");
          }
        }
      }
    }//GEN-LAST:event_jButtonAddTeacherActionPerformed

    private void jTextFieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNameFocusLost
      if (jTextFieldName.getText().length() > Defs.nameLength || jTextFieldName.getText().length() == 0) {
        jLabelWarningName.setForeground(Color.red);
        wrongFormat |= 1;
      } else {
        jLabelWarningName.setForeground(Color.black);
        wrongFormat &= 30;
      }
    }//GEN-LAST:event_jTextFieldNameFocusLost

    private void jTextFieldFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameFocusLost
      if (jTextFieldFirstName.getText().length() > Defs.stringLength || jTextFieldFirstName.getText().length() == 0) {
        jLabelWarningFirstName.setForeground(Color.red);
        wrongFormat |= 2;
      } else {
        jLabelWarningFirstName.setForeground(Color.black);
        wrongFormat &= 29;
      }
    }//GEN-LAST:event_jTextFieldFirstNameFocusLost

    private void jTextFieldSecondNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSecondNameFocusLost
//        if (jTextFieldSecondName.getText().length() > Defs.stringLength) {
//            jLabelWarningSecondName.setForeground(Color.red);
//            wrongFormat |= 4;
//        } else {
//      jLabelWarningSecondName.setForeground(Color.black);
//      wrongFormat &= 27;
//        }
    }//GEN-LAST:event_jTextFieldSecondNameFocusLost

    private void jFormattedTextFieldNifFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNifFocusLost
      if (jFormattedTextFieldNif.getText().contains(" ")/* && !Defs.isValidNif(jFormattedTextFieldNif.getText())*/) {
        jLabelWarningNif.setForeground(Color.red);
        wrongFormat |= 8;
      } else {
        jLabelWarningNif.setForeground(Color.black);
        wrongFormat &= 23;
      }
    }//GEN-LAST:event_jFormattedTextFieldNifFocusLost

    private void jFormattedTextFieldPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPhoneFocusLost
      if (!jFormattedTextFieldPhone.getText().matches("(\\d){3}\\s(\\d){3}\\s(\\d){3}")) {
        jLabelWarningPhone.setForeground(Color.red);
        wrongFormat |= 16;
      } else {
        jLabelWarningPhone.setForeground(Color.black);
        wrongFormat &= 15;
      }
    }//GEN-LAST:event_jFormattedTextFieldPhoneFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddTeacher;
    private javax.swing.JFormattedTextField jFormattedTextFieldNif;
    private javax.swing.JFormattedTextField jFormattedTextFieldPhone;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNif;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelSecondName;
    private javax.swing.JLabel jLabelTitleForm;
    private javax.swing.JLabel jLabelWarningFirstName;
    private javax.swing.JLabel jLabelWarningName;
    private javax.swing.JLabel jLabelWarningNif;
    private javax.swing.JLabel jLabelWarningPhone;
    private javax.swing.JLabel jLabelWarningSecondName;
    private javax.swing.JSeparator jSeparatorTitleForm;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSecondName;
    // End of variables declaration//GEN-END:variables
    private final BodyGUI body;
  private int wrongFormat = 31;
}
